apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
  namespace: taskmanager
data:
  AUTH_SERVICE_URL: http://auth-service:8081
  TASK_SERVICE_URL: http://task-service:8082
  FRONTEND_URL: https://taskmanager.example.com
