spring.application.name=task-service

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

security.token.secret=taskmanager-secret-key-2026

server.port=${SERVER_PORT:8082}
# PostgreSQL config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://task-db:5432/task_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
